### ISSUE TITLE
Missing nullability check

### ISSUE THREAD

**Issue by btihanyi** [mehditalebidev/DotnetMappersBenchmark#1]
I've noticed that the `NestedTypeMapping.Mappers.InLineMapping()` method doesn't check the `Address` property's nullability. The code should be similar to this:

``` csharp
var userDto = new UserDto()
{
    Address = user.Address == null ? null : new AddressDto()
    {
        City = user.Address.City,
        Street = user.Address.Street
    }
};
```

I've seen that all three mappers handle with this.

**Comment by mehditalebidev** [comment]
That went over my head. I have fixed it now. Thanks a lot.
